In [1]:
import numpy as np 
import pandas as pd 


from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import metrics
import seaborn as sns
import matplotlib.pyplot as plt
import keras
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import GridSearchCV

# ignore Warning
import warnings
warnings.filterwarnings("ignore") 

Using TensorFlow backend.


In [2]:
df_train = pd.read_csv('files_csv/train.csv')
df_test = pd.read_csv('files_csv/test.csv')

In [3]:
df_test['Id']

0       1461
1       1462
2       1463
3       1464
4       1465
        ... 
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: Id, Length: 1459, dtype: int64

#### Features fortement corrélés avec SalePrice

In [4]:
cols = ['SalePrice','OverallQual', 'GrLivArea', 'GarageCars', 'FullBath', 'YearBuilt']

In [5]:
df_train = df_train[cols]
# # dummy values
# df_train = pd.get_dummies(df_train) => que des numériques ??? 
# Na -> moyenne de la colonne
df_train = df_train.fillna(df_train.mean())
df_train

SalePrice  OverallQual  GrLivArea  GarageCars  FullBath  YearBuilt
0        208500            7       1710           2         2       2003
1        181500            6       1262           2         2       1976
2        223500            7       1786           2         2       2001
3        140000            7       1717           3         1       1915
4        250000            8       2198           3         2       2000
...         ...          ...        ...         ...       ...        ...
1455     175000            6       1647           2         2       1999
1456     210000            6       2073           2         2       1978
1457     266500            7       2340           1         2       1941
1458     142125            5       1078           1         1       1950
1459     147500            5       1256           1         1       1965

[1460 rows x 6 columns]

#### StandardScaler train

In [6]:
# standard scale
scale = StandardScaler()
X_train = df_train[['OverallQual', 'GrLivArea', 'GarageCars', 'FullBath', 'YearBuilt']]
X_train = scale.fit_transform(X_train)
X_train

array([[ 0.65147924,  0.37033344,  0.31172464,  0.78974052,  1.05099379],
       [-0.07183611, -0.48251191,  0.31172464,  0.78974052,  0.15673371],
       [ 0.65147924,  0.51501256,  0.31172464,  0.78974052,  0.9847523 ],
       ...,
       [ 0.65147924,  1.56964722, -1.02685765,  0.78974052, -1.00249232],
       [-0.79515147, -0.83278768, -1.02685765, -1.02604084, -0.70440562],
       [-0.79515147, -0.49393395, -1.02685765, -1.02604084, -0.20759447]])

In [7]:
y_train = df_train['SalePrice'].values
y_train

array([208500, 181500, 223500, ..., 266500, 142125, 147500])

#### Seed

In [8]:
# seed = 42
# np.random.seed(seed)

#### Split train/val

In [9]:
# X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.33, random_state=seed)

#### Model

In [10]:
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(200, input_dim=X_train.shape[1], kernel_initializer='normal', activation='relu'))
    model.add(Dense(100, kernel_initializer='normal', activation='relu'))
    model.add(Dense(50, kernel_initializer='normal', activation='relu'))
    model.add(Dense(25, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='normal'))
    # Compile model
    model.compile(loss='mean_squared_error', optimizer=keras.optimizers.Adadelta())
    return model

In [11]:
# model = KerasRegressor(build_fn=create_model)
# epochs = np.array([10, 50,90])
# batches = np.array([1,10,30])
# param_grid = dict(nb_epoch=epochs, batch_size=batches)
# grid = GridSearchCV(estimator=model, param_grid=param_grid)
# grid_result = grid.fit(X_train,y_train)

In [12]:
# print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

In [13]:
model = create_model()
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 200)               1200      
_________________________________________________________________
dense_2 (Dense)              (None, 100)               20100     
_________________________________________________________________
dense_3 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_4 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 26        
Total params: 27,651
Trainable params: 27,651
Non-trainable params: 0
_________________________________________________________________


In [14]:
history = model.fit(X_train, y_train, epochs=150, batch_size=1)

Epoch 1/150
1460/1460 [==============================] - 2s 2ms/step - loss: 3074303556.7712
Epoch 2/150
1460/1460 [==============================] - 2s 2ms/step - loss: 1402883317.7262
Epoch 3/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1388252810.0060
Epoch 4/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1376548123.3275
Epoch 5/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1368802856.5476
Epoch 6/150
1460/1460 [==============================] - 2s 2ms/step - loss: 1363387410.6508
Epoch 7/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1319241093.9363
Epoch 8/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1336722765.3875
Epoch 9/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1319217070.8729
Epoch 10/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1306532869.3098
Epoch 11/150
1460/1460 [==============================] - 2s 1ms/step

1460/1460 [==============================] - 2s 1ms/step - loss: 1254526450.8783
Epoch 89/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1262356371.1440
Epoch 90/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1252852843.9284
Epoch 91/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1242022994.7814
Epoch 92/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1230663702.6225
Epoch 93/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1269551263.4619
Epoch 94/150
1460/1460 [==============================] - 3s 2ms/step - loss: 1232474961.2289
Epoch 95/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1230408095.6876
Epoch 96/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1239810983.0175
Epoch 97/150
1460/1460 [==============================] - 2s 1ms/step - loss: 1246666019.6504
Epoch 98/150
1460/1460 [==============================] - 2s 2ms/step - l

#### traitement sur le fichier Test

In [16]:
cols = ['OverallQual', 'GrLivArea', 'GarageCars', 'FullBath', 'YearBuilt']
test_ID = df_test['Id'].values.tolist()
df_test = df_test[cols]
df_test = df_test.fillna(df_test.mean())

In [17]:
X_test = df_test.values
# scale , mais pourquoi on réutilise pas celui utilisé sur X_train ? 
# scale = StandardScaler()
X_test = scale.fit_transform(X_test)
X_test

array([[-0.75110125, -1.21558782, -0.98801273, -1.02871967, -0.34094461],
       [-0.05487716, -0.32353941, -0.98801273, -1.02871967, -0.43969491],
       [-0.75110125,  0.29450799,  0.30162251,  0.77308345,  0.844059  ],
       ...,
       [-0.75110125, -0.539856  ,  0.30162251, -1.02871967, -0.37386137],
       [-0.75110125, -1.06313613, -2.27764797, -1.02871967,  0.67947517],
       [ 0.64134693,  1.0588266 ,  1.59125775,  0.77308345,  0.71239193]])

#### Prédiction

In [18]:
prediction = model.predict(X_test)

In [19]:
submission = pd.DataFrame()
submission['Id'] = test_ID
submission['SalePrice'] =  prediction
submission.to_csv('Keras-5features.csv', index=False)